language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("URIParser")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
