function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(URIParser.parse_url, (String,))
    precompile(URIParser.parse_authority, (String, Bool,))
    precompile(URIParser.call, (Array{Any, 1}, Type{URIParser.URI}, URIParser.URI,))
    precompile(URIParser.escape_with, (String, String,))
    precompile(URIParser.call, (Type{URIParser.URI}, String, String, UInt16, String, String, String, String, Bool,))
    precompile(URIParser.is_host_char, (Char,))
    precompile(URIParser.is_url_char, (Char,))
    precompile(URIParser.isnum, (Char,))
    precompile(URIParser.is_mark, (Char,))
    precompile(URIParser.is_userinfo_char, (Char,))
    precompile(URIParser.escape, (String,))
    precompile(URIParser.call, (Type{URIParser.URI}, String,))
    precompile(URIParser.ishex, (Char,))
end
